/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_test1_Jni */

#ifndef _Included_com_baidu_test1_Jni
#define _Included_com_baidu_test1_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_test1_Jni
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_test1_Jni_stringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
